### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by verhasi** [AndreyVMarkelov/jira-groovioli#2]
Hi Andrey,

On the marketplace the referred license is https://opensource.org/licenses/bsd-license.php but in the source code there is no license mentioned at all.

Regards,
Istvan

**Comment by AndreyVMarkelov** [comment]
@verhasi can you help me how to put it right way?

**Comment by verhasi** [comment]
Unintentionally  added to the existing pull request the proposed solution for the license as well.

**Comment by AndreyVMarkelov** [comment]
Hi. Can you please provide example what to put into file?

12 Янв 2018 г. 21:06 пользователь "verhasi" <notifications@github.com>
написал:
