### ISSUE TITLE
Validators don't work

### ISSUE THREAD

**Issue by darmarius** [AndreyVMarkelov/jira-groovioli#8]
Hi Andrey,
I'm interested in your plugin and found after test this issue. I tried to use versions from Marketplace and built by myself, but no success.

**Comment by AndreyVMarkelov** [comment]
Hi. Let's fix that. Could you please provide example and jira version

**Comment by darmarius** [comment]
I'm running on JIRA v7.9.1 and script like that:
false
P.S. that script works with scriptrunner.

**Comment by AndreyVMarkelov** [comment]
Ah. It is different.

For validators you should throws exceptions
throw new InvalidInputException("fixVersions", "Please specify Fix Version/s")

only for conditions you can use boolean return

**Comment by darmarius** [comment]
Is this restriction due to the absence of an AbstractJiraValidator class?

**Comment by AndreyVMarkelov** [comment]
No. I have implemented that way. I think I can fix that
