### ISSUE TITLE
Update for Jira 8.0 compatibility

### ISSUE THREAD

**Issue by radicand** [AndreyVMarkelov/jira-groovioli#9]
I've just upgraded to Jira 8.0 and noticed the plugin is now showing as incompatible. What's required to publish an 8.0 compatible update?

**Comment by AndreyVMarkelov** [comment]
Done

**Comment by radicand** [comment]
Thanks for taking a look at this - is there a code branch with the changes required for Jira 8 / marketplace update? I don't see anything new in the repo since Feb 20.

**Comment by AndreyVMarkelov** [comment]
Hello. I will update today

пн, 25 мар. 2019 г., 20:28 Nick Pappas <notifications@github.com>:
